# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='handy.User')),
                ('user_joblist', models.ManyToManyField(related_name='joblist', to='handy.User')),
            ],
        ),
    ]
